[package]
name = "untitled60"
version = "2.1.0"
authors = ["bacef <abacefabmicroblast@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
